/*
LTJS: Source port of LithTech Jupiter System
Copyright (c) 2021-2026 Boris I. Bendovsky (bibendovsky@hotmail.com) and Contributors
SPDX-License-Identifier: GPL-2.0
*/

// DirectInput key constants

#ifndef LTJS_DINPUT_INCLUDED
#define LTJS_DINPUT_INCLUDED

constexpr int DIK_ESCAPE = 0x01;
constexpr int DIK_1 = 0x02; // On main keyboard
constexpr int DIK_2 = 0x03; // On main keyboard
constexpr int DIK_3 = 0x04; // On main keyboard
constexpr int DIK_4 = 0x05; // On main keyboard
constexpr int DIK_5 = 0x06; // On main keyboard
constexpr int DIK_6 = 0x07; // On main keyboard
constexpr int DIK_7 = 0x08; // On main keyboard
constexpr int DIK_8 = 0x09; // On main keyboard
constexpr int DIK_9 = 0x0A; // On main keyboard
constexpr int DIK_0 = 0x0B; // On main keyboard
constexpr int DIK_MINUS = 0x0C; // On main keyboard
constexpr int DIK_EQUALS = 0x0D; // On main keyboard
constexpr int DIK_BACK = 0x0E; // BACKSPACE
constexpr int DIK_TAB = 0x0F;
constexpr int DIK_Q = 0x10;
constexpr int DIK_W = 0x11;
constexpr int DIK_E = 0x12;
constexpr int DIK_R = 0x13;
constexpr int DIK_T = 0x14;
constexpr int DIK_Y = 0x15;
constexpr int DIK_U = 0x16;
constexpr int DIK_I = 0x17;
constexpr int DIK_O = 0x18;
constexpr int DIK_P = 0x19;
constexpr int DIK_LBRACKET = 0x1A; // Left square bracket [
constexpr int DIK_RBRACKET = 0x1B; // Right square bracket ]
constexpr int DIK_RETURN = 0x1C; // ENTER on main keyboard
constexpr int DIK_LCONTROL = 0x1D; // Left CTRL
constexpr int DIK_A = 0x1E;
constexpr int DIK_S = 0x1F;
constexpr int DIK_D = 0x20;
constexpr int DIK_F = 0x21;
constexpr int DIK_G = 0x22;
constexpr int DIK_H = 0x23;
constexpr int DIK_J = 0x24;
constexpr int DIK_K = 0x25;
constexpr int DIK_L = 0x26;
constexpr int DIK_SEMICOLON = 0x27;
constexpr int DIK_APOSTROPHE = 0x28;
constexpr int DIK_GRAVE = 0x29; // Grave accent (`)
constexpr int DIK_LSHIFT = 0x2A; // Left SHIFT
constexpr int DIK_BACKSLASH = 0x2B;
constexpr int DIK_Z = 0x2C;
constexpr int DIK_X = 0x2D;
constexpr int DIK_C = 0x2E;
constexpr int DIK_V = 0x2F;
constexpr int DIK_B = 0x30;
constexpr int DIK_N = 0x31;
constexpr int DIK_M = 0x32;
constexpr int DIK_COMMA = 0x33;
constexpr int DIK_PERIOD = 0x34; // On main keyboard
constexpr int DIK_SLASH = 0x35; // Forward slash (/) on main keyboard
constexpr int DIK_RSHIFT = 0x36; // Right SHIFT
constexpr int DIK_MULTIPLY = 0x37; // Asterisk (*) on numeric keypad
constexpr int DIK_LMENU = 0x38; // Left ALT
constexpr int DIK_SPACE = 0x39; // SPACEBAR
constexpr int DIK_CAPITAL = 0x3A; // CAPS LOCK
constexpr int DIK_F1 = 0x3B;
constexpr int DIK_F2 = 0x3C;
constexpr int DIK_F3 = 0x3D;
constexpr int DIK_F4 = 0x3E;
constexpr int DIK_F5 = 0x3F;
constexpr int DIK_F6 = 0x40;
constexpr int DIK_F7 = 0x41;
constexpr int DIK_F8 = 0x42;
constexpr int DIK_F9 = 0x43;
constexpr int DIK_F10 = 0x44;
constexpr int DIK_NUMLOCK = 0x45;
constexpr int DIK_SCROLL = 0x46; // SCROLL LOCK
constexpr int DIK_NUMPAD7 = 0x47;
constexpr int DIK_NUMPAD8 = 0x48;
constexpr int DIK_NUMPAD9 = 0x49;
constexpr int DIK_SUBTRACT = 0x4A; // MINUS SIGN (-) on numeric keypad
constexpr int DIK_NUMPAD4 = 0x4B;
constexpr int DIK_NUMPAD5 = 0x4C;
constexpr int DIK_NUMPAD6 = 0x4D;
constexpr int DIK_ADD = 0x4E; // PLUS SIGN (+) on numeric keypad
constexpr int DIK_NUMPAD1 = 0x4F;
constexpr int DIK_NUMPAD2 = 0x50;
constexpr int DIK_NUMPAD3 = 0x51;
constexpr int DIK_NUMPAD0 = 0x52;
constexpr int DIK_DECIMAL = 0x53; // PERIOD (decimal point) on numeric keypad
//constexpr int DIK_OEM_102 = 0x56; // On British and German keyboards
constexpr int DIK_F11 = 0x57;
constexpr int DIK_F12 = 0x58;
constexpr int DIK_F13 = 0x64; // On NEC PC-98 Japanese keyboard
constexpr int DIK_F14 = 0x65; // On NEC PC-98 Japanese keyboard
constexpr int DIK_F15 = 0x66; // On NEC PC-98 Japanese keyboard
//constexpr int DIK_KANA = 0x70; // On Japanese keyboard
//constexpr int DIK_ABNT_C1 = 0x73; // On numeric pad of Brazilian keyboards
//constexpr int DIK_CONVERT = 0x79; // On Japanese keyboard
//constexpr int DIK_NOCONVERT = 0x7B; // On Japanese keyboard
//constexpr int DIK_YEN = 0x7D; // On Japanese keyboard
//constexpr int DIK_ABNT_C2 = 0x7E; // On numeric pad of Brazilian keyboards
//constexpr int DIK_NUMPADEQUALS = 0x8D; // On numeric keypad of NEC PC-98 Japanese keyboard
//constexpr int DIK_PREVTRACK = 0x90; // Previous track; circumflex on Japanese keyboard
//constexpr int DIK_AT = 0x91; // On Japanese keyboard
//constexpr int DIK_COLON = 0x92; // On Japanese keyboard
//constexpr int DIK_UNDERLINE = 0x93; // On NEC PC-98 Japanese keyboard
//constexpr int DIK_KANJI = 0x94; // On Japanese keyboard
//constexpr int DIK_STOP = 0x95; // On NEC PC-98 Japanese keyboard
//constexpr int DIK_AX = 0x96; // On Japanese keyboard
//constexpr int DIK_UNLABELED = 0x97; // On Japanese keyboard
//constexpr int DIK_NEXTTRACK = 0x99; // Next track
constexpr int DIK_NUMPADENTER = 0x9C;
constexpr int DIK_RCONTROL = 0x9D; // Right CTRL
//constexpr int DIK_MUTE = 0xA0;
//constexpr int DIK_CALCULATOR = 0xA1;
//constexpr int DIK_PLAYPAUSE = 0xA2;
//constexpr int DIK_MEDIASTOP = 0xA4;
//constexpr int DIK_VOLUMEDOWN = 0xAE;
//constexpr int DIK_VOLUMEUP = 0xB0;
//constexpr int DIK_WEBHOME = 0xB2;
//constexpr int DIK_NUMPADCOMMA = 0xB3; // On numeric keypad of NEC PC-98 Japanese keyboard
constexpr int DIK_DIVIDE = 0xB5; // Forward slash (/) on numeric keypad
constexpr int DIK_SYSRQ = 0xB7;
constexpr int DIK_RMENU = 0xB8; // Right ALT
constexpr int DIK_PAUSE = 0xC5;
constexpr int DIK_HOME = 0xC7;
constexpr int DIK_UP = 0xC8; // UP ARROW
constexpr int DIK_PRIOR = 0xC9; // PAGE UP
constexpr int DIK_LEFT = 0xCB; // LEFT ARROW
constexpr int DIK_RIGHT = 0xCD; // RIGHT ARROW
constexpr int DIK_END = 0xCF;
constexpr int DIK_DOWN = 0xD0; // DOWN ARROW
constexpr int DIK_NEXT = 0xD1; // PAGE DOWN
constexpr int DIK_INSERT = 0xD2;
constexpr int DIK_DELETE = 0xD3;
//constexpr int DIK_LWIN = 0xDB; // Left Windows logo key
//constexpr int DIK_RWIN = 0xDC; // Right Windows logo key
//constexpr int DIK_APPS = 0xDD; // Application key
//constexpr int DIK_POWER = 0xDE;
//constexpr int DIK_SLEEP = 0xDF;
//constexpr int DIK_WAKE = 0xE3;
//constexpr int DIK_WEBSEARCH = 0xE5;
//constexpr int DIK_WEBFAVORITES = 0xE6; // Displays the Microsoft Internet Explorer Favorites list, the Windows Favorites folder, or the Netscape Bookmarks list.
//constexpr int DIK_WEBREFRESH = 0xE7;
//constexpr int DIK_WEBSTOP = 0xE8;
//constexpr int DIK_WEBFORWARD = 0xE9;
//constexpr int DIK_WEBBACK = 0xEA;
//constexpr int DIK_MYCOMPUTER = 0xEB;
//constexpr int DIK_MAIL = 0xEC;
//constexpr int DIK_MEDIASELECT = 0xED; // Media Select key, which displays a selection of supported media players on the system

#endif // LTJS_DINPUT_INCLUDED
