//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Launcher.rc
//
#define IDS_APPNAME                     1
#define IDS_APPEXE                      2
#define IDS_DISPLAY_WARNING             3
#define IDS_OPTIONS_WARNING             4
#define IDS_APPCD1CHECK                 5
#define IDS_APPCD2CHECK                 6
#define IDS_REZBASE                     7
#define IDS_SETUPEXE                    8
#define IDS_SERVEREXE                   9
#define IDS_LANGUAGE                    10
#define IDS_INSERTCD2                   11
#define IDS_INSERTCD                    12
#define IDS_CANTLAUNCHSETUP             13
#define IDS_NORENS                      14
#define IDS_HELP_DISABLESOUND           15
#define IDS_HELP_DISABLEMUSIC           16
#define IDS_HELP_DISABLEMOVIES          17
#define IDS_HELP_DISABLEFOG             18
#define IDS_HELP_DISABLEJOYSTICKS       19
#define IDS_HELP_DISABLETRIPLEBUFFERING 20
#define IDS_HELP_DISABLEHARDWARECURSOR  21
#define IDS_HELP_DISABLEANIMATEDLOADSCREEN 22
#define IDS_HELP_RESTOREDEFAULTS        23
#define IDS_HELP_ALWAYSSPECIFY          24
#define IDS_CANTFINDREZFILE             25
#define IDS_CANTLAUNCHCLIENTEXE         26
#define IDS_DETAIL_HEADER               27
#define IDS_DETAIL_LOW                  28
#define IDS_DETAIL_MEDIUM               29
#define IDS_DETAIL_HIGH                 30
#define IDS_CANTLAUNCHSERVER            31
#define IDS_APPVERSION                  32
#define IDS_CANTUNINSTALL               33
#define IDS_COMPANYWEBPAGE              34
#define IDS_CANTOPENAVI                 35
#define IDS_PUBLISHERWEBPAGE            36
#define IDS_OD_DISABLESOUND             37
#define IDS_OD_DISABLEMUSIC             38
#define IDS_OD_DISABLEMOVIES            39
#define IDS_OD_DISABLEFOG               40
#define IDS_OD_DISABLEJOYSTICKS         41
#define IDS_OD_DISABLETRIPLEBUFFERING   42
#define IDS_OD_DISABLEHARDWARECURSOR    43
#define IDS_OD_DISABLEANIMATEDLOADSCREENS 44
#define IDS_OD_RESTOREDEFAULTS          45
#define IDS_OD_ALWAYSSPECIFY            46
#define IDS_DEBUG_REGCREATEERROR        47
#define IDS_DEBUG_INSTALLSUCCESS        48
#define IDS_DEBUG_UNINSTALLSUCCESS      49
#define IDS_LAUNCHBROWSERERROR          50
#define IDS_HELP_DEFAULT                51
#define IDS_HELP_DISABLEHARDWARESOUND   52
#define IDS_HELP_DISABLESOUNDFILTERS    53
#define IDS_OD_DISABLEHARDWARESOUND     54
#define IDS_OD_DISABLESOUNDFILTERS		55
#define IDD_LAUNCHER_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDB_BACKGROUND                  130
#define IDD_MULTIPLAYER_DIALOG          145
#define IDD_OPTIONS_DIALOG              146
#define IDB_MD_BACKGROUND               146
#define IDD_DISPLAY_DIALOG              147
#define IDD_MESSAGEBOX                  148
#define IDD_DETAILSETTINGS_DIALOG       149
#define IDB_OD_BACKGROUND               164
#define IDB_DD_BACKGROUND               219
#define IDR_AVI_BUTTONS                 221
#define IDR_AVI_LOGO1                   222
#define IDR_AVI_LOGO2                   223
#define IDR_SELECT                      225
#define IDR_CLICK                       226
#define IDR_ANIMDLG                     228
#define IDR_BUTTONDOWN                  278
#define IDR_TYPE                        279
#define IDR_TYPE2                       280
#define IDR_TYPE3                       281
#define IDR_TYPEBACK                    282
#define IDB_MB_BACKGROUND               283
#define IDB_DSD_BACKGROUND              284
#define IDR_INTRO                       294
#define IDB_INFORMATION                 296
#define IDB_ERROR                       297
#define IDB_WARNING                     298
#define IDC_WEBHAND                     308
#define IDR_AVI_OK                      317
#define IDC_MP_HOST                     1001
#define IDC_MP_JOIN                     1002
#define IDC_CLOSE                       1003
#define IDC_MP_FIND                     1003
#define IDC_MINIMIZE                    1004
#define IDC_MP_SERVER                   1004
#define IDC_MP_BACK                     1005
#define IDC_MP_CLOSE                    1006
#define IDC_DISPLAY                     1007
#define IDC_QUIT                        1008
#define IDC_PLAY                        1009
#define IDC_MULTIPLAYER                 1010
#define IDC_SERVER                      1010
#define IDC_OPTIONS                     1011
#define IDC_OD_CLOSE                    1012
#define IDC_UNINSTALL                   1012
#define IDC_OD_DISABLESOUND             1014
#define IDC_OD_DISABLEMUSIC             1015
#define IDC_OD_DISABLEMOVIES            1016
#define IDC_COMMANDLINE                 1017
#define IDC_OD_DISABLEFOG               1018
#define IDC_OD_DISABLETRIPLEBUFFERING   1019
#define IDC_OD_DISABLEJOYSTICKS         1020
#define IDC_OD_DISABLEHARDWARECURSOR    1021
#define IDC_OD_DISABLEANIMATEDLOADSCREEN 1022
#define IDC_OD_RESTOREDEFAULTSETTINGS   1023
#define IDC_OD_ALWAYSSPECIFY            1024
#define IDC_OD_DISABLEHARDWARESOUND     1025
#define IDC_ANIMATE                     1026
#define IDC_ANIMATE2                    1027
#define IDC_OD_DISABLESOUNDFILTERS      1028
#define IDC_OD_OK                       1030
#define IDC_OD_CANCEL                   1031
#define IDC_OD_HELP                     1032
#define IDC_DD_CLOSE                    1034
#define IDC_DD_OK                       1035
#define IDC_RENDERER_LIST               1038
#define IDC_DISPLAY_LIST                1039
#define IDC_RESOLUTION_LIST             1040
#define IDC_DD_CANCEL                   1041
#define IDC_MB_OK                       1043
#define IDC_MB_CANCEL                   1044
#define IDC_MB_CLOSE                    1045
#define IDC_CAPTION                     1046
#define IDC_TEXT                        1047
#define IDC_HELPTEXT                    1047
#define IDC_DSD_CANCEL                  1048
#define IDC_DSD_HIGH                    1049
#define IDC_DSD_MEDIUM                  1050
#define IDC_DSD_LOW                     1051
#define IDC_DSD_CLOSE                   1052
#define IDC_HEADERTEXT                  1053
#define IDC_LOWTEXT                     1054
#define IDC_MEDIUMTEXT                  1055
#define IDC_HIGHTEXT                    1056
#define IDC_MONOLITH                    1058
#define IDC_COMPANYWEB                  1058
#define IDC_PUBLISHERWEB                1059
#define IDC_MB_ICON                     1067

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        320
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
