#define __WON_MASTER_CPP__
#include "createaccountop.cpp"
#include "dbproxyop.cpp"
#include "getaccountop.cpp"
#include "getuseridfromnameop.cpp"
#include "profiledata.cpp"
#include "requestaccountinfoemailop.cpp"
#include "requestpasswordemailop.cpp"
#include "updateaccountop.cpp"
